@startuml

# TODO: estimate following model:

1. Efforts investment

# TODO: code engineer => content maker
# TODO: code => content

code engineer spends time => produces code === value === qualification * time_spent === man/hour * hour_price

engineer -> code -> value -> project_value + value, engineer_share + value
# content value estimated before start and may be corrected in the end
value -> value_pay + value_share  # value split depending on project stage, engineer's agreement and money pool
money_pool - value_pay,  engineer + value_pay, engineer_share + value_share

2. Money investment

Investor gives money => money goes to money pool => money === value

investor - money -> value=money -> money_pool + value, investor_share + value * 0.9, project_value + value * 0.1

3. Management and revenue

manager -> sales -> income
multiplicator = income / (1-discount) --> 0.0 .. +infinity
sales_pool + multiplicator
manager_share += (sum(multiplicator)-sales_count) / target_sales_pool    # ?Logarithmic?
# discount_price - price that were set as initial discount
multiplicator_pool += multiplicator
manager_income = income * 0.1   # ?Logarithmic?
project_income = income * 0.9   # ?Logarithmic?
revenue = project_income - outsiders spends

4. Revenue

project brings money => money split and part goes to money pool, other part goes to dividends

revenue -> money -> value
value -> value_pool + value_dividends   # Value is split depending on project stage, money pool and share holders will
money_pool + value_pool
foreach shareholder:
  shareholder_money + money + value_dividends * shareholder_share / (project_value)  # TODO: + ?money_pool?

5. Vote share

Vote share:
* 30% to code investors (according to code share),
* 30% to money investors (according to money share),
* 30% to management investors (according to conversion share)
* 10% to product owner

or

Vote share:
* 24.99% to code investors (according to code share),
* 24.99% to money investors (according to money share),
* 24.99% to management investors (according to conversion share)
* 25.03% to product owner


6. Exit value

actives -> sell -> money -> money_pool + money
passives -> sell -> money -> money_pool + money
foreach shareholder:
    shareholder_money + (money_pool + (exit_price * project_value)) * (shareholder_share / project_value)

@enduml
